geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path


app_name = "adminapp"

urlpatterns = [
    path("users/create/", adminapp.UserCreateView.as_view(), name="user_create"),
    path("users/read/", adminapp.UserListView.as_view(), name="users"),
    path(
        "users/update/<int:pk>/", adminapp.UserUpdateView.as_view(), name="user_update"
    ),
    path(
        "users/delete/<int:pk>/", adminapp.UserDeleteView.as_view(), name="user_delete"
    ),
    path("categories/create/", adminapp.category_create, name="category_create"),
    path("categories/read/", adminapp.categories, name="categories"),
    path(
        "categories/update/<int:pk>/", adminapp.category_update, name="category_update"
    ),
    path(
        "categories/delete/<int:pk>/", adminapp.category_delete, name="category_delete"
    ),
    path(
        "products/create/category/<int:pk>/",
        adminapp.ProductCreateView.as_view(),
        name="product_create",
    ),
    path("products/read/category/<int:pk>/", adminapp.products, name="products"),
    path("products/read/<int:pk>/", adminapp.product_read, name="product_read"),
    path("products/update/<int:pk>/", adminapp.product_update, name="product_update"),
    path("products/delete/<int:pk>/", adminapp.product_delete, name="product_delete"),
]

geekshop/authapp/urls.py
from django.urls import path, re_path
from . import views

app_name = "authapp"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    re_path(
        r"^verify/(?P<email>.+)/(?P<activation_key>\w+)", views.verify, name="verify"
    ),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from mainapp import views as mainapp


urlpatterns = [
    # path("admins/", admin.site.urls),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("", mainapp.index, name="main"),
    path("contact/", mainapp.contact, name="contact"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("", include("social_django.urls", namespace="social")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from authapp.forms import ShopUserEditForm, ShopUserRegisterForm
from authapp.models import ShopUser
from django import forms
from mainapp.models import ProductCategory, Product


class ShopUserEditAdminForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = "__all__"


class ShopUserCreateAdminForm(ShopUserRegisterForm):
    class Meta:
        model = ShopUser
        fields = "__all__"


class ProductCategoryAdminForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

geekshop/adminapp/views/category.py
from django.shortcuts import get_object_or_404, render
from mainapp.models import ProductCategory
from adminapp.forms import ProductCategoryAdminForm
from adminapp.utils import superuser_required
from django.http.response import HttpResponseRedirect
from django.urls import reverse


@superuser_required
def category_create(request):
    if request.method == "POST":
        form = ProductCategoryAdminForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("admin:categories"))
    else:
        form = ProductCategoryAdminForm()

    return render(
        request,
        "adminapp/category/edit.html",
        context={
            "title": "Создание категории",
            "form": form,
        },
    )


@superuser_required
def categories(request):
    categories = ProductCategory.objects.all().order_by("id")
    return render(
        request,
        "adminapp/category/categories.html",
        context={
            "objects": categories,
            "title": "Категории",
        },
    )


@superuser_required
def category_update(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == "POST":
        form = ProductCategoryAdminForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("admin:categories"))
    else:
        form = ProductCategoryAdminForm(instance=category)

    return render(
        request,
        "adminapp/category/edit.html",
        context={
            "title": "Создание категории",
            "form": form,
        },
    )


@superuser_required
def category_delete(request, pk):
    title = "категории/удаление"
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == "POST":
        category.delete()
        return HttpResponseRedirect(reverse("admin:categories"))

    content = {"title": title, "category_to_delete": category}
    return render(request, "adminapp/category/delete.html", content)

geekshop/adminapp/views/product.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory
from adminapp.utils import superuser_required
from django.views.generic import CreateView
from django.utils.decorators import method_decorator
from django.urls import reverse
from adminapp.forms import ProductEditForm
from django.http.response import HttpResponseRedirect


class ProductCreateView(CreateView):
    model = Product
    template_name = "adminapp/product/edit.html"
    fields = "__all__"

    def get_success_url(self):
        return reverse("admin:products", kwargs=self.kwargs)

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        return {"category": self.get_category()}

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs["pk"])

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.get_category()
        return context


@superuser_required
def products(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    products = Product.objects.filter(category=category).order_by("id")
    return render(
        request,
        "adminapp/product/products.html",
        context={
            "objects": products,
            "category": category,
            "title": "Продукты",
        },
    )


@superuser_required
def product_read(request, pk):
    title = "продукт/подробнее"
    product = get_object_or_404(Product, pk=pk)
    content = {
        "title": title,
        "object": product,
    }

    return render(request, "adminapp/product/product_read.html", content)


def product_create(request, pk):
    title = "продукт/создание"
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == "POST":
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse("admin:products", args=[pk]))
    else:
        product_form = ProductEditForm(initial={"category": category})
        content = {"title": title, "update_form": product_form, "category": category}

    return render(request, "adminapp/product/edit.html", content)


@superuser_required
def product_update(request, pk):
    title = "продукт/редактирование"

    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(
                reverse("admin:product_update", args=[edit_product.pk])
            )
    else:
        edit_form = ProductEditForm(instance=edit_product)

    content = {
        "title": title,
        "update_form": edit_form,
        "category": edit_product.category,
    }

    return render(request, "adminapp/product/edit.html", content)


@superuser_required
def product_delete(request, pk):
    title = "продукт/удаление"

    product = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        product.is_active = False
        product.save()
        return HttpResponseRedirect(
            reverse("admin:products", args=[product.category.pk])
        )

    content = {"title": title, "product_to_delete": product}

    return render(request, "adminapp/product/delete.html", content)

geekshop/adminapp/views/user.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from authapp.models import ShopUser
from adminapp.utils import superuser_required
from django.utils.decorators import method_decorator
from adminapp.forms import ShopUserCreateAdminForm, ShopUserEditAdminForm
from django.urls import reverse_lazy


class UserCreateView(CreateView):
    model = ShopUser
    template_name = "adminapp/user/edit.html"
    form_class = ShopUserCreateAdminForm
    success_url = reverse_lazy("admin:users")

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        contex["title"] = "Создание пользователя"
        return super().get_context_data(**kwargs)


class UserListView(ListView):
    model = ShopUser
    template_name = "adminapp/user/users.html"

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        contex["title"] = "Список пользователей"
        return super().get_context_data(**kwargs)


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = "adminapp/user/edit.html"
    form_class = ShopUserEditAdminForm
    success_url = reverse_lazy("admin:users")

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        contex["title"] = "Редактирование пользователя"
        return super().get_context_data(**kwargs)


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = "adminapp/user/delete.html"
    success_url = reverse_lazy("admin:users")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        contex["title"] = "Удаление пользователя"
        return super().get_context_data(**kwargs)

geekshop/adminapp/templates/adminapp/product/delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="product_read">
    <div class="product_name">
      Продукт<strong>{{ object.category.name|title }} / 
                     {{ object.name|title }}</strong> 
    </div>
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
         alt="{{ object.name }}">
    <div class="summary">
      <b>цена</b>
      <p>{{ object.price }} руб</p>
      <b>количество</b>
      <p>{{ object.quantity }}</p>
      <b>в каталоге</b>
      <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
      <p>
        <button>
          <a href={% url 'admin:product_update' object.pk %}>
            редактировать
          </a>
        </button>
      </p>
      <p>
        <button>
            <a href={% url 'admin:product_delete' object.pk %}>
              удалить
            </a>
          </button>
        </p>
        <p>
          <button>
            <a href={% url 'admin:products' object.category.pk %}>
              назад
            </a>
          </button>
        </p>
      </div>
      <div class="product_desc">
        <b>краткая информация</b>
        <p>{{ object.short_desc }}</p>
        <br><br>
        <b>подробная информация</b>
        <p>{{ object.description }}</p>
      </div>
    </div>
  {% endblock %}

geekshop/adminapp/templates/adminapp/product/edit.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:products' category.pk %}">
      к списку товаров категории
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/product/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="product_read">
    <div class="product_name">
      Продукт<strong>{{ object.category.name|title }} / 
                     {{ object.name|title }}</strong> 
    </div>
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
         alt="{{ object.name }}">
    <div class="summary">
      <b>цена</b>
      <p>{{ object.price }} руб</p>
      <b>количество</b>
      <p>{{ object.quantity }}</p>
      <b>в каталоге</b>
      <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
      <p>
        <button>
          <a href={% url 'admin:product_update' object.pk %}>
            редактировать
          </a>
        </button>
      </p>
      <p>
        <button>
            <a href={% url 'admin:product_delete' object.pk %}>
              удалить
            </a>
          </button>
        </p>
        <p>
          <button>
            <a href={% url 'admin:products' object.category.pk %}>
              назад
            </a>
          </button>
        </p>
      </div>
      <div class="product_desc">
        <b>краткая информация</b>
        <p>{{ object.short_desc }}</p>
        <br><br>
        <b>подробная информация</b>
        <p>{{ object.description }}</p>
      </div>
    </div>
  {% endblock %}
  

geekshop/adminapp/templates/adminapp/product/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="products_list">
    <button class="new_product">
      <a href={% url 'admin:product_create' category.pk %}>
        новый продукт
      </a>
    </button>
		
    {% for object in objects %}
      <div class="product_record">
        <img 
          src="/media/{{object.image|default:'products_images/default.jpg'}}"
          alt="{{ object.name }}">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href={% url 'admin:product_read' object.pk %}>
              подробнее
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}