geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path


app_name = "adminapp"

urlpatterns = [
    path("users/create/", adminapp.UserCreateView.as_view(), name="user_create"),
    path("users/read/", adminapp.UserListView.as_view(), name="users"),
    path(
        "users/update/<int:pk>/", adminapp.UserUpdateView.as_view(), name="user_update"
    ),
    path(
        "users/delete/<int:pk>/", adminapp.UserDeleteView.as_view(), name="user_delete"
    ),
    path("categories/create/", adminapp.category_create, name="category_create"),
    path("categories/read/", adminapp.categories, name="categories"),
    path(
        "categories/update/<int:pk>/", adminapp.category_update, name="category_update"
    ),
    path(
        "categories/delete/<int:pk>/", adminapp.category_delete, name="category_delete"
    ),
    path(
        "products/create/category/<int:pk>/",
        adminapp.ProductCreateView.as_view(),
        name="product_create",
    ),
    path("products/read/category/<int:pk>/", adminapp.products, name="products"),
    path("products/read/<int:pk>/", adminapp.product_read, name="product_read"),
    path("products/update/<int:pk>/", adminapp.product_update, name="product_update"),
    path("products/delete/<int:pk>/", adminapp.product_delete, name="product_delete"),
]

geekshop/authapp/urls.py
from django.urls import path, re_path
from . import views

app_name = "authapp"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    re_path(
        r"^verify/(?P<email>.+)/(?P<activation_key>\w+)", views.verify, name="verify"
    ),
]

geekshop/basketapp/urls.py
from django.urls import path
from . import views


app_name = "basketapp"

urlpatterns = [
    path("", views.view, name="view"),
    path("add/<int:product_id>/", views.add, name="add"),
    path("remove/<int:basket_item_id>/", views.remove, name="remove"),
    path("edit/<int:basket_item_id>/<int:quantity>/", views.edit, name="edit"),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from mainapp import views as mainapp


urlpatterns = [
    # path("admins/", admin.site.urls),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("", mainapp.index, name="main"),
    path("contact/", mainapp.contact, name="contact"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("", include("social_django.urls", namespace="social")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from . import views


app_name = "mainapp"

urlpatterns = [
    path("", views.products, name="all"),
    path("<int:pk>", views.category, name="category"),
    path("<int:pk>/<int:page>", views.category, name="page_category"),
    path("product/<int:product_id>", views.product, name="product"),
]

geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import path

app_name = "ordersapp"

urlpatterns = [
    path("", ordersapp.OrderList.as_view(), name="orders_list"),
    path(
        "forming/complete/<int:pk>)",
        ordersapp.order_forming_complete,
        name="order_forming_complete",
    ),
    path("create/", ordersapp.OrderCreate.as_view(), name="order_create"),
    path("read/<int:pk>/", ordersapp.OrderDetail.as_view(), name="order_read"),
    path("update/<int:pk>/", ordersapp.OrderUpdate.as_view(), name="order_update"),
    path("delete/<int:pk>/", ordersapp.OrderDelete.as_view(), name="order_delete"),
    path("product/<int:pk>/price/", ordersapp.product_price, name="product_price")
]

geekshop/mainapp/models.py
from distutils.command.upload import upload
from email.mime import image
from turtle import color
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="Имя", max_length=100)
    description = models.TextField(verbose_name="Описание", blank=True)

    def __str__(self):
        return self.name


class ProductManager(models.Manager):

    def active_items(self):
        return Product.objects.filter(is_active=True)


class Product(models.Model):
    name = models.CharField(verbose_name="Имя", max_length=100)
    price = models.DecimalField(
        verbose_name="Цена", max_digits=7, decimal_places=2, default=0
    )
    color = models.CharField(verbose_name="Цвет", max_length=8, default="0x000000")
    description = models.TextField(verbose_name="Описание", blank=True)
    image = models.ImageField(verbose_name="Картинка", blank=True, upload_to="products")
    quantity = models.PositiveIntegerField(verbose_name="Количество", default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    is_active = models.BooleanField(verbose_name="Активный", default=True)

    objects = ProductManager()

    def __str__(self):
        return self.name

geekshop/mainapp/views.py
import random
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage
from django.utils import timezone
from .models import Product, ProductCategory


def get_hot_product(queryset):
    return random.choice(queryset)


def index(request):
    products = Product.objects.all()[:4]
    return render(
        request,
        "mainapp/index.html",
        context={
            "title": "Главная",
            "date": timezone.now,
            "products": products,
        },
    )


def contact(request):
    return render(
        request,
        "mainapp/contact.html",
        context={
            "title": "Контакты",
            "date": timezone.now,
        },
    )


def products(request):
    catigories = ProductCategory.objects.all()
    products = Product.objects.all()
    hot_product = get_hot_product(products)
    return render(
        request,
        "mainapp/products.html",
        context={
            "title": "Продукты",
            "hot_product": hot_product,
            "products": products.exclude(pk=hot_product.pk)[:4],
            "date": timezone.now,
            "catigories": catigories,
        },
    )


def product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    catigories = ProductCategory.objects.all()
    return render(
        request,
        "mainapp/product.html",
        context={
            "product": product,
            "category": product.category,
            "title": "Продукты",
            "catigories": catigories,
        },
    )


def category(request, pk, page=1):
    catigories = ProductCategory.objects.all()
    category = get_object_or_404(ProductCategory, pk=pk)
    products = Product.objects.filter(category=category)
    hot_product = get_hot_product(products)
    paginator = Paginator(products.exclude(pk=hot_product.pk), 3)
    try:
        products_page = paginator.page(page)
    except EmptyPage:
        products_page = paginator.page(paginator.num_pages)
    return render(
        request,
        "mainapp/products.html",
        context={
            "title": "Продукты",
            "hot_product": get_hot_product(products),
            "paginator": paginator,
            "page": products_page,
            "products": products_page,
            "date": timezone.now,
            "catigories": catigories,
            "category": category,
        },
    )

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'products:all' %}" 
            class="{% if request.resolver_match.view_name == 'products:all' %} active {% endif %}">Все</a></li>
        {% for category in catigories %}
        <li><a href="{% url 'products:category' category.id %}" 
            class="{% if request.resolver_match.view_name == 'products:category' and request.resolver_match.kwargs.pk == category.id %}
             active
             {% endif %}"
             >{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</div>

geekshop/mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'main' %}" class="logo"></a>
<ul class="menu">
    {% for link in main_menu_links %}
    <li><a href="{% url link.url %}" 
        {% if request.resolver_match.view_name in link.active %}
            class="active"
        {% endif %}
        >
            {{ link.name }}
        </a></li>
    {% endfor %}
        {% if user.is_authenticated %}
    <li>
        <div class="dropdown">
            <a class="dropdown-toggle" href="" data-toggle="dropdown">
                {{ user.first_name|default:'Пользователь' }}      
                <span class="caret"></span>    
            </a>
            <ul class="dropdown-menu">
                <li class="dropdown-item">
                    <a href="{% url 'auth:edit' %}">
                        профиль
                    </a>
                </li>
                <li class="dropdown-item">
                    <a href="{% url 'ordersapp:orders_list' %}">
                        заказы
                    </a>
                </li>
            </ul>
        </div>
    </li>
    {% if user.is_superuser %}
    <li>
        <a href="{% url 'admin:users' %}">
            Админка       
        </a>
    </li>
    {% endif %}
    {% comment %} {% endif %}
    {% if user.is_authenticated %} {% endcomment %}
    <li>
        <a href="{% url 'basket:view' %}">
            <i class="fa fa-shopping-basket"></i>
            {{ user.basket.total_cost }} руб. ({{ user.basket.total_quantity }})

        </a>
    </li>
    {% endif %}

    <li>
        {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
        <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>


</ul>
<a href="#" class="search"></a>
<a href="#" class="basket"></a>

geekshop/mainapp/templates/mainapp/includes/inc_products.html
{% if paginator %}
	{% if page.has_previous %}
		<a href="{% url 'products:paged_category' category.id page.previous_page_number %">Сюда</a>
	{% endif %}
	Страница {{ page.number }} из {{ paginator.num_pages }} 
	{% if page.has_next %}
	<a href="{% url 'products:paged_category' category.id page.previous_page_next %">Туда</a>
	{% endif %}
{% endif %}
{{ products.num_pages }}
{% for product in products %}
{% load static %}
		<div class="block">
			<a href="{% url 'products:product' product.id %}"><img class="product-image" src="/media/{{ product.image }}" alt=""> 
				<div class="text">
					<img src="{% static 'img/icon-hover.png' %}" alt="img">
					<h4>{{ product.name }}</h4>
					<p>{{ product.description }}</p>
				</div> 
			</a>
		</div>
		{% endfor %}