geekshop/authapp/urls.py
from django.urls import path, re_path
from . import views

app_name = "authapp"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    re_path(
        r"^verify/(?P<email>.+)/(?P<activation_key>\w+)", views.verify, name="verify"
    ),
]

geekshop/basketapp/urls.py
from django.urls import path
from . import views


app_name = "basketapp"

urlpatterns = [
    path("", views.view, name="view"),
    path("add/<int:product_id>/", views.add, name="add"),
    path("remove/<int:basket_item_id>/", views.remove, name="remove"),
    path("edit/<int:basket_item_id>/<int:quantity>/", views.edit, name="edit"),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from mainapp import views as mainapp


urlpatterns = [
    # path("admins/", admin.site.urls),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("", mainapp.index, name="main"),
    path("contact/", mainapp.contact, name="contact"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("", include("social_django.urls", namespace="social")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from . import views


app_name = "mainapp"

urlpatterns = [
    path("", views.products, name="all"),
    path("<int:pk>", views.category, name="category"),
    path("<int:pk>/<int:page>", views.category, name="page_category"),
    path("product/<int:product_id>", views.product, name="product"),
]

geekshop/mainapp/models.py
from distutils.command.upload import upload
from email.mime import image
from turtle import color
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="Имя", max_length=100)
    description = models.TextField(verbose_name="Описание", blank=True)

    def __str__(self):
        return self.name


class ProductManager(models.Manager):

    def active_items(self):
        return Product.objects.filter(is_active=True)


class Product(models.Model):
    name = models.CharField(verbose_name="Имя", max_length=100)
    price = models.DecimalField(
        verbose_name="Цена", max_digits=7, decimal_places=2, default=0
    )
    color = models.CharField(verbose_name="Цвет", max_length=8, default="0x000000")
    description = models.TextField(verbose_name="Описание", blank=True)
    image = models.ImageField(verbose_name="Картинка", blank=True, upload_to="products")
    quantity = models.PositiveIntegerField(verbose_name="Количество", default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    is_active = models.BooleanField(verbose_name="Активный", default=True)

    objects = ProductManager()

    def __str__(self):
        return self.name

geekshop/adminapp/views/product.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory
from adminapp.utils import superuser_required
from django.views.generic import CreateView
from django.utils.decorators import method_decorator
from django.urls import reverse
from adminapp.forms import ProductEditForm
from django.http.response import HttpResponseRedirect


class ProductCreateView(CreateView):
    model = Product
    template_name = "adminapp/product/edit.html"
    fields = "__all__"

    def get_success_url(self):
        return reverse("admin:products", kwargs=self.kwargs)

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        return {"category": self.get_category()}

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs["pk"])

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.get_category()
        return context


@superuser_required
def products(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    products = Product.objects.filter(category=category).order_by("id")
    return render(
        request,
        "adminapp/product/products.html",
        context={
            "objects": products,
            "category": category,
            "title": "Продукты",
        },
    )


@superuser_required
def product_read(request, pk):
    title = "продукт/подробнее"
    product = get_object_or_404(Product, pk=pk)
    content = {
        "title": title,
        "object": product,
    }

    return render(request, "adminapp/product/product_read.html", content)


def product_create(request, pk):
    title = "продукт/создание"
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == "POST":
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse("admin:products", args=[pk]))
    else:
        product_form = ProductEditForm(initial={"category": category})
        content = {"title": title, "update_form": product_form, "category": category}

    return render(request, "adminapp/product/edit.html", content)


@superuser_required
def product_update(request, pk):
    title = "продукт/редактирование"

    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(
                reverse("admin:product_update", args=[edit_product.pk])
            )
    else:
        edit_form = ProductEditForm(instance=edit_product)

    content = {
        "title": title,
        "update_form": edit_form,
        "category": edit_product.category,
    }

    return render(request, "adminapp/product/edit.html", content)


@superuser_required
def product_delete(request, pk):
    title = "продукт/удаление"

    product = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        product.is_active = False
        product.save()
        return HttpResponseRedirect(
            reverse("admin:products", args=[product.category.pk])
        )

    content = {"title": title, "product_to_delete": product}

    return render(request, "adminapp/product/delete.html", content)

geekshop/mainapp/views.py
import random
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage
from django.utils import timezone
from .models import Product, ProductCategory


def get_hot_product(queryset):
    return random.choice(queryset)


def index(request):
    products = Product.objects.all()[:4]
    return render(
        request,
        "mainapp/index.html",
        context={
            "title": "Главная",
            "date": timezone.now,
            "products": products,
        },
    )


def contact(request):
    return render(
        request,
        "mainapp/contact.html",
        context={
            "title": "Контакты",
            "date": timezone.now,
        },
    )


def products(request):
    catigories = ProductCategory.objects.all()
    products = Product.objects.all()
    hot_product = get_hot_product(products)
    return render(
        request,
        "mainapp/products.html",
        context={
            "title": "Продукты",
            "hot_product": hot_product,
            "products": products.exclude(pk=hot_product.pk)[:4],
            "date": timezone.now,
            "catigories": catigories,
        },
    )


def product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    catigories = ProductCategory.objects.all()
    return render(
        request,
        "mainapp/product.html",
        context={
            "product": product,
            "category": product.category,
            "title": "Продукты",
            "catigories": catigories,
        },
    )


def category(request, pk, page=1):
    catigories = ProductCategory.objects.all()
    category = get_object_or_404(ProductCategory, pk=pk)
    products = Product.objects.filter(category=category)
    hot_product = get_hot_product(products)
    paginator = Paginator(products.exclude(pk=hot_product.pk), 3)
    try:
        products_page = paginator.page(page)
    except EmptyPage:
        products_page = paginator.page(paginator.num_pages)
    return render(
        request,
        "mainapp/products.html",
        context={
            "title": "Продукты",
            "hot_product": get_hot_product(products),
            "paginator": paginator,
            "page": products_page,
            "products": products_page,
            "date": timezone.now,
            "catigories": catigories,
            "category": category,
        },
    )

geekshop/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
	<link rel="stylesheet" href="{% static "css/font-awesome.css" %}">
    <script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    
</head>
<body>
	<div class="container">
            
            {% block header %}
            !!!Заголовок!!!
            {% endblock %}
            {% block content %}
            !!!Контент!!!
            {% endblock  %}
            
		



		<div class="clr"></div>
	</div>	

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017. Текущая дата и время: {{ date }}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>	
			
</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% block header %}
<div class="hero">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
	<h1>наши контакты</h1>
</div>
{% endblock %}

{% block content %}
<div class="location">
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block header %}
<div class="slider">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
	<div class="text-slider">
		<h3 class="green">тенденции</h3>
		<h3 class="big"> удобные стулья</h3>
		<p>Новый уровень комфорта. Отличные характеристики.</p>
		<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
	</div>	
	<div class="navi">
		<a href="#"></a><a href="#"></a><a href="#"></a>
	</div>
</div>
{% endblock %}

{% block content %}
<div class="featured">
	<div class="featured-menu">
			<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
	</div>
	<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
	<div class="clearfix">
	</div>
	<div class="tab-content">
		{% include 'mainapp/includes/inc_products.html' %}
	</div>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block header %}
<div class="hero-white">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
</div>
{% endblock  %}

{% block content %}
<div class="details">
	{% include 'mainapp/includes/inc_categories_menu.html' %}
{% if product %}
	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{{ product.image.url }}">
			</div>
			<div class="slider-control">
				<div class="block">
					<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
			</div>
		</div>

		<div class="description">
			<h3 class="big-bold">{{ product.name }}</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price"> {{ product.price }} <span>руб</span></p>
			<a href="{% url 'basket:add' product.id %}" class="red-button">
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				{{ hot_product.description|linebreaks }} 
			</div>
		</div>
	</div>
{% endif %}

</div>
{% endblock  %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block header %}
<div class="hero-white">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
</div>
{% endblock  %}

{% block content %}
<div class="details">
	<div class="links clearfix">
		<ul class="links-menu">
			<li><a href="{% url 'products:all' %}" 
				class="{% if request.resolver_match.view_name == 'products:all' %} active {% endif %}">Все</a></li>
			{% for category in catigories %}
			<li><a href="{% url 'products:category' category.id %}" 
				class="{% if request.resolver_match.view_name == 'products:category' and request.resolver_match.kwargs.pk == category.id %}
				 active
				 {% endif %}"
				 >{{ category.name }}</a></li>
			{% endfor %}
		</ul>
	</div>

	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{% static 'img/slider1.jpg' %}">
			</div>
			<div class="slider-control">
				<div class="block">
					<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
						<div class="text"></div>
					</a>
				</div>
			</div>
		</div>

		<div class="description">
			<h3 class="big-bold">Отличный стул</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price"> 2585.9 <span>руб</span></p>
			<a href="#" class="red-button">
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				<p>Расположитесь комфортно.</p> 
				<p>Отличное качество материалов
				позволит вам это.</p> 
				<p>Различные цвета</p>
				<p>высочайший уровень
				эргономики и прочность.</p>
			</div>
		</div>
	</div>

	<div class="related">
		<div class="title clearfix">
			<h2>Похожие продукты</h2>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
		</div>
		<div class="related-products clearfix">
			{% include 'mainapp/includes/inc_products.html' %}

		</div>
	</div>
</div>
{% endblock  %}